# Generated by Django 4.2.1 on 2023-05-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_login_rename_queries_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Queries',
        ),
    ]
