# Generated by Django 4.2.1 on 2023-05-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contact_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='psw',
        ),
    ]
