# Generated by Django 4.2.1 on 2023-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=122)),
                ('type_ques', models.CharField(max_length=122)),
                ('com_ques', models.CharField(max_length=20)),
                ('pdf', models.FileField(null=True, upload_to='static\\pdf')),
            ],
        ),
    ]
