# Generated by Django 4.2.1 on 2023-06-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_qna_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='com_ques',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='type_ques',
        ),
    ]
