# Generated by Django 4.2.1 on 2023-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_qna_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
