# Generated by Django 4.2.1 on 2023-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_qna_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='sub_name',
        ),
        migrations.AlterField(
            model_name='qna',
            name='pdf',
            field=models.FileField(null=True, upload_to='static/pdf/'),
        ),
    ]
